# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#

def fib(values, limit)
  if values.empty?
    fib([0, 1], limit)
  elsif (next_val = values.last + values[-2]) < limit
    fib(values << next_val, limit)
  else
    values
  end
end

fib_values = fib([], 4_000_000)

puts fib_values.select(&:even?).sum

# => 4613732

